
spring:
  application:
    name: travel-server
  datasource:
    druid:
      url: jdbc:mysql://192.168.80.134:3306/traveldb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  type-aliases-package: cn.yunhe.travel.pojo
  mapper-locations: classpath:mappers/*.xml
pagehelper:
  reasonable: true
  helper-dialect: mysql
logging:
  config: classpath:logback.xml
server:
  port: 8088
